=== amaggat/INT3505-21/src/XML-XSD/pcprofileschema.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">

    <xs:element name="pcprofile">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cpu" type="xs:string" />
                <xs:element name="mainboard" type="xs:string" />
                <xs:element name="cooler" type="xs:string" />
                <xs:element name="rams">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="ram" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="drives">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hard-disk-drives">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="hdd" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="solid-state-drives">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ssd" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="gpu" type="xs:string" />
                <xs:element name="power-supply-unit" type="xs:string" />
                <xs:element name="case" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== amaggat/INT3505-21/src/XML-XSD/pcprofile-false.xml
<?xml version="1.0"?>

<pcprofile
        xmlns="https://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.w3schools.com/xml pcprofileschema.xsd"
>

    <!-- element cpud is not allowed here -->
    <cpud>Intel Core i5-10400</cpud>

    <mainboard>ASUS TUF GAMING B460M-PLUS</mainboard>

    <cooler>Noctua NH - U14S</cooler>

    <rams>
        <ram>RAM Kingston HyperX Fury Black 8GB DDR4 2666MHz</ram>
        <ram>RAM Kingston HyperX Fury Black 8GB DDR4 2666MHz</ram>
    </rams>

    <drives>
        <hard-disk-drives>
            <hdd>HDD WD Blue 1TB 7200rpm</hdd>
        </hard-disk-drives>

        <solid-state-drives>
            <ssd>SSD Kioxia Exceria 2.5" Sata III 240GB</ssd>
        </solid-state-drives>
    </drives>

    <gpu>GIGABYTE AORUS GeForce RTX 3060 Ti MASTER 8G</gpu>

    <power-supply-unit>Nguá»“n Cooler Master V650 SFX - 80 Plus Gold - Full Modular</power-supply-unit>

    <case>MSI MAG VAMPIRIC 100R</case>
</pcprofile>
