=== amaggat/INT3505-21/src/XML-XSD/student.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">

    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="dob" type="xs:date"/>
                <xs:element name="student-id" type="xs:unsignedInt"/>
                <xs:element name="gender" type="xs:string"/>
                <xs:element name="email" type="xs:string"/>
                <xs:element name="contacts">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="contact">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="address" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== amaggat/INT3505-21/src/XML-XSD/students.xml
<?xml version="1.0"?>

<student
        xmlns="https://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.w3schools.com/xml student.xsd"
>

    <name>Trần Trung Thành</name>

    <dob>2000-09-18</dob>

    <student-id>18021174</student-id>

    <gender>Male</gender>

    <email>18021174@vnu.edu.vn</email>

    <contacts>

        <contact>

            <name>Trần Văn ABC</name>

            <address>Đông Anh, Hà Nội</address>

        </contact>

        <contact>

            <name>Nguyễn Thị XYZ</name>

            <address>Đông Anh, Hà Nội</address>

        </contact>

    </contacts>

</student>
